services:
  postgres:
    image: postgres:15.2-bullseye
    container_name: postgres
    restart: always
    volumes:
      - "postgresdb_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "dev"
    ports:
      - "5431:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6378:6379"
    networks:
      - app-network

  todo-api:
    build: ./api
    container_name: todo-api
    image: todo-api
    ports:
      - "7979:7979"
    networks:
      - app-network
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/dev"
    depends_on:
      - postgres

  next-app:
    build: ./next-app
    container_name: next-app
    image: next-app
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      BACKEND_API_BASE_URL: "http://todo-api:7979"
      NEXT_PUBLIC_REOWN_PROJECT_ID: "c3f9c053752e031f7cfd17bd9ee19577"
      MORALIS_API_KEY: ""

networks:
  app-network:
    driver: bridge

volumes:
  postgresdb_data:
